#ifndef DSP_ERROR_H
#define DSP_ERROR_H

enum dsp_error {
    DSP_ERR_PATH_NOT_EMPTY,
    DSP_ERR_NO_PERMISSION,
    DSP_ERR_INVALID_CONFIG,
    DSP_ERR_INVALID_FORMAT,
    DSP_ERR_CONNECT,
    DSP_ERR_NO_KEY,
};

#endif
